<a href="https://colab.research.google.com/github/akhilamoh/AML-331-Python-and-Machine-Learning-Lab/blob/main/5a_usingfunction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a=list()
b=list()
print("for matrix A")
n=int(input("enter the no of rows"))
m=int(input("enter the no of column"))
print("for matrix B")
p=int(input("enter the no of rows"))
q=int(input("enter the no of column"))
if m==p:
  print("------multiplication possible------")
  print("enter elements for matrix A")
  for i in range(n):
    for i in range(m):
      a.append(int(input()))
  x=np.array(a)
  y=x.reshape(n,m)
  print (y)
  print("enter elements for matrix B")
  for i in range(p):
    for i in range(q):
      b.append(int(input()))
  u=np.array(b)
  v=u.reshape(p,q)
  print (v)
  print(np.multiply(y,v))
else:
  print("---not possible-----2")

for matrix A
enter the no of rows2
enter the no of column2
for matrix B
enter the no of rows2
enter the no of column2
------multiplication possible------
enter elements for matrix A
5
1
4
0
[[5 1]
 [4 0]]
enter elements for matrix B
4
5
6
0
[[4 5]
 [6 0]]
[[20  5]
 [24  0]]
